FROM node:14

# Install ffmpeg and python3
RUN apt-get update && apt-get install -y ffmpeg python3 python3-pip

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

# Ensure the build directory exists
RUN mkdir -p /usr/src/app/public

# Build the frontend if necessary (assuming you have a build step)
# RUN npm run build --prefix public

EXPOSE 5000

# Start the server
CMD [ "node", "index.js" ]